### PR TITLE
Strings

### PR DESCRIPTION
**Pull request by mattcontest**
# 13 - 12 - 2024
## 67. Add Binary
Description: This problem gives us two binary numbers in string format, and our aim is to add them together.
We will take advantage of ord() to calculate the integer value of each character. By doing so, we can then add their values, calculate the respective carry, and include it in the result as we construct our final solution.

Loom: [loom link](https://www.loom.com/share/be44b18673cb412ab685ce4c9503be6a?sid=b0aff3ea-8e21-4013-83b3-af619d7fa4c8) 

## 242.  Valid Anagrams
Description: In this problem, we are tasked with determining whether two strings are valid anagrams.
Two strings are considered valid anagrams if they contain the same characters with the exact same frequencies, even if the order of the characters is different.

Loom: [loom link](https://www.loom.com/share/73fb993f5e3d4071add705f9e0ac6bdf) 

## 13.  Roman to Integer
Description: In this problem, we are tasked with converting a Roman numeral into an integer.
We will use a dictionary to map each Roman numeral to its corresponding integer value and handle the conversion based on Roman numeral rules. One important rule is that if a smaller numeral is placed before a larger one, it must be subtracted from the larger numeral. We will use the indices `i` and `i+1` to process the Roman numeral string accordingly.

Loom: [loom link](https://www.loom.com/share/547413d81386454a8efd022aed8aff1e?sid=e5e45965-4bd0-488b-ab45-019f8be9a695) 

## 14.  Longest Common Prefix
Description: We are tasked with finding the Longest Common Prefix among an array of strings.We will use an iterative nested for loop to compare characters across all strings. First, we initialize an empty string `result` to store the common prefix. The outer for loop iterates over the characters of the first string in `strs`. The inner for loop iterates through all the strings in the array to check for matches. In the inner loop, we evaluate two conditions:
1) If `i` equals the length of the current string:
   - This means we’ve reached the end of that string. Since there are no more characters
     to match, we return `result` as the common prefix.
2) If `string[i] != strs[0][i]`:
    - This means the character at index `i` in the current string doesn’t match the
      corresponding character in the first string. At this point, we return `result`.
As long as neither condition is triggered, we append matching characters to `result`.

Once the loops have completed or one of the conditions is met, we return `result` as the Longest Common Prefix.

Loom: [loom link](https://www.loom.com/share/fd45b55f6d75421f84a633995ba9cfc5) 

## 680.  Valid Palindrome II
Description: This problem involves checking if a string can become a palindrome by removing at most one character.
To solve this, we will use the two-pointer technique to evaluate the string from both ends.
We will iterate over the string using a while loop until the pointers meet or cross.
Inside the loop, we will check if the characters at `l` and `r` are not the same.
If there's a mismatch, we try skipping one character (either `s[l]` or `s[r]`)
If no mismatches are found, or skipping one character resolves the issue, return True
Loom: [loom link](https://www.loom.com/share/1446e5bef8d64d87ba316bfaed8a8ec0?sid=ae466498-2798-4c37-99ea-d581a6f6b49a) 

## 1347. Minimum Number of Steps to Make Two Strings Anagram
Description: The goal of this problem is to determine the minimum number of steps required to make the string `t` an anagram of the string `s`. An anagram is a word or phrase formed by rearranging the letters of another, meaning both strings must contain the same characters with the same frequencies. To solve this, we will:
1) Count the frequency of each character in both strings.
2) Calculate how many characters in `t` need to be replaced to match the frequency of characters in `s`.

Loom: [loom link](https://www.loom.com/share/26871858062846d8b35267e8b71c6a37?sid=428e8d4a-2828-4487-a7fb-37eb685a2813)

### CODE REVIEW

**Review by CoachTimVan — COMMENTED** [review]
Your PR structure is very well done! Code looks good for the most part, and comments and descriptions are perfect. Let's keep that up! However, your linter is still failing, let's make sure that all of that is corrected.

**Review by CoachTimVan — CHANGES_REQUESTED** [review]
Please update your code such that the linter is passing.

**Comment by mattcontest** [comment]
Thank you! I have addressed all the Pylint issues and passed all the checks. Shall I proceed with merging

**Review by CoachTimVan — APPROVED** [review]
Perfect looks good!

**Pull request merged**
